### ISSUE TITLE
Token renewal fails with org.springframework.core.task.TaskRejectedException

### ISSUE THREAD

**Issue by ixe013** [spring-projects/spring-vault#108]
We have an application that uses an autowired `EnvironmentVaultConfiguration` with AppRole Authentication. This is our properties file:

```
vault.authentication=APPROLE
vault.app-role.role-id=c9e372ff-31cc-207f-5204-8d6619eb1666
vault.app-role.secret-id=9156856b-d6c6-8e2c-14f6-d699f71cae0e
```

The application authenticates and gets a token from the AppRole authentication back end. Whenever we use the token, a renewal is scheduled, which is expected from the documentation. But the schedule always fails with a `org.springframework.core.task.TaskRejectedException` exception (stack trace below).

Could it be related to this? What can I do to fix it?

```
2017-06-20 15:58:39.011  INFO 4892 --- [nio-8443-exec-4] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService  'threadPoolTaskScheduler'
2017-06-20 16:00:22.636  INFO 4892 --- [nio-8443-exec-4] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@19106e2: startup date [Tue Jun 20 15:58:38 EDT 2017]; root of context hierarchy
2017-06-20 16:00:22.636  INFO 4892 --- [nio-8443-exec-4] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'threadPoolTaskScheduler'
```

The full stack trace:
```
org.springframework.core.task.TaskRejectedException: Executor [java.util.concurrent.ScheduledThreadPoolExecutor@1cea740[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]] did not accept task: org.springframework.vault.authentication.LifecycleAwareSessionManager$1@326993
	at org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler.schedule(ThreadPoolTaskScheduler.java:304) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.vault.authentication.LifecycleAwareSessionManager.scheduleTask(LifecycleAwareSessionManager.java:219) ~[spring-vault-core-1.0.0.RELEASE.jar:na]
	at org.springframework.vault.authentication.LifecycleAwareSessionManager.scheduleRenewal(LifecycleAwareSessionManager.java:215) ~[spring-vault-core-1.0.0.RELEASE.jar:na]
	at org.springframework.vault.authentication.LifecycleAwareSessionManager.getSessionToken(LifecycleAwareSessionManager.java:168) ~[spring-vault-core-1.0.0.RELEASE.jar:na]
	at org.springframework.vault.core.VaultTemplate$1.intercept(VaultTemplate.java:136) ~[spring-vault-core-1.0.0.RELEASE.jar:na]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:86) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.vault.client.VaultClients$1.intercept(VaultClients.java:104) ~[spring-vault-core-1.0.0.RELEASE.jar:na]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:86) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:70) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:380) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.vault.core.VaultTemplate.write(VaultTemplate.java:253) ~[spring-vault-core-1.0.0.RELEASE.jar:na]
```

**Comment by mp911de** [comment]
`AnnotationConfigApplicationContext` was closed in which the `ThreadPoolTaskScheduler` lives. Can you elaborate a bit on your context structure? It looks as if you're closing the context but keep the `VaultTemplate` instance using.

**Comment by ixe013** [comment]
Indeed, that was it! 

We had this code that created an `AnnotationConfigApplicationContext` every time: 

```
try(final AbstractApplicationContext ctx = new AnnotationConfigApplicationContext(VaultConfig.class)) {
    VaultTemplate context = ctx.getBean(VaultTemplate.class);
    return new VaultFacadeImpl(context);
}
```

`VaultFacadeImpl` really just provides an abstration over `VaultTemplate::read` and `VaultTemplate::write`. Now `VaultFacadeImpl` creates and keeps its own `AnnotationConfigApplicationContext` and `VaultTemplate`. To test, I've set the AppRole token TTL to an insane 10s, and I saw my request work and the token renewed:

```
2017-06-20 23:08:14.273  INFO 5064 --- [nio-8443-exec-3] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService  'threadPoolTaskScheduler'
2017-06-20 23:08:14.567  INFO 5064 --- [nio-8443-exec-3] o.s.v.a.LifecycleAwareSessionManager     : Scheduling Token renewal
2017-06-20 23:08:14.589  INFO 5064 --- [nio-8443-exec-3] c.c.c.kes.health.HealthController        : Vault test succeeded
2017-06-20 23:08:14.589  INFO 5064 --- [nio-8443-exec-3] c.c.c.kes.health.HealthController        : Returning status
2017-06-20 23:08:14.608 DEBUG 5064 --- [nio-8443-exec-3] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@1fbf8a7
2017-06-20 23:08:39.576  INFO 5064 --- [TaskScheduler-1] o.s.v.a.LifecycleAwareSessionManager     : Renewing token
2017-06-20 23:08:39.677  INFO 5064 --- [TaskScheduler-1] o.s.v.a.LifecycleAwareSessionManager     : Scheduling Token renewal
2017-06-20 23:09:04.681  INFO 5064 --- [TaskScheduler-1] o.s.v.a.LifecycleAwareSessionManager     : Renewing token
2017-06-20 23:09:04.773  INFO 5064 --- [TaskScheduler-1] o.s.v.a.LifecycleAwareSessionManager     : Scheduling Token renewal
2017-06-20 23:09:25.178 DEBUG 5064 --- [io-8443-exec-10] o.s.b.w.f.OrderedRequestContextFilter    : Bound request context to thread: org.apache.catalina.connector.RequestFacade@1fbf8a7
2017-06-20 23:09:25.179  WARN 5064 --- [io-8443-exec-10] c.c.c.k.s.TokenAuthenticationService     : Header Authorization missing from request, will be anonymous
2017-06-20 23:09:25.180  INFO 5064 --- [io-8443-exec-10] c.c.c.kes.health.HealthController        : Got Health Request
2017-06-20 23:09:25.180  INFO 5064 --- [io-8443-exec-10] c.c.c.kes.health.HealthController        : Testing Database
2017-06-20 23:09:25.180  INFO 5064 --- [io-8443-exec-10] c.c.c.kes.health.HealthController        : Testing Vault
2017-06-20 23:09:25.226  INFO 5064 --- [io-8443-exec-10] c.c.c.kes.health.HealthController        : Vault test succeeded
2017-06-20 23:09:25.227  INFO 5064 --- [io-8443-exec-10] c.c.c.kes.health.HealthController        : Returning status
2017-06-20 23:09:25.230 DEBUG 5064 --- [io-8443-exec-10] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@1fbf8a7
2017-06-20 23:09:29.779  INFO 5064 --- [TaskScheduler-1] o.s.v.a.LifecycleAwareSessionManager     : Renewing token
2017-06-20 23:09:29.804  INFO 5064 --- [TaskScheduler-1] o.s.v.a.LifecycleAwareSessionManager     : Scheduling Token renewal
```
