### ISSUE TITLE
Connect to Cloud Config Server with Vault&Git  using Approle authentication for vault

### ISSUE THREAD

**Issue by heyitsaakash** [spring-projects/spring-vault#152]
I have a cloud config server which picks up data from git and vault. It was working fine for the tokenbased authentication. I used to provide the spring.cloud.config.token=419113c3-d058-faca-4965-b6e03a918a28 value from command line. I want to move to "Approle" based authentication. I created vault app role assigned it the new policy allowing read, write etc. I am able to login through the Vault CLI using ROLEID and Secret ID parameters. Following the links.
https://www.vaultproject.io/docs/auth/approle.html

When i get the token from Command line and i provide the same through the parameter to my spring microserverice it is able to connect to the config server and fetch the information. However, when i replace the information in my client with values below it doesn't work. My new role is testrole i tried giving whole path to approle/role/testrole and testrole but that too didn't work.

spring.cloud.vault.authentication=APPROLE
spring.cloud.vault.app-role.role-id=a9d80e12-0fcb-7955-28d1-ac596053eaef
spring.cloud.vault.app-role.secret-id=c48b728d-2f9b-f47a-7349-42a76032f153
spring.cloud.vault.app-role.app-auth-path=approle

---------------------------------------------
Error
-10-05 12:09:48.921  INFO [sku-microservice,,,] 8808 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:1010/
2017-10-05 12:09:50.276  INFO [sku-microservice,,,] 8808 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:1010/
2017-10-05 12:09:51.764  INFO [sku-microservice,,,] 8808 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:1010/
2017-10-05 12:09:51.789 ERROR [sku-microservice,,,] 8808 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:132) ~[spring-cloud-config-client-2.0.0.M1.jar:2.0.0.M1]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$FastClassBySpringCGLIB$$fa44b2a.invoke(<generated>) ~[spring-cloud-config-client-2.0.0.M1.jar:2.0.0.M1]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747) ~[spring-aop-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:91) ~[spring-retry-1.2.1.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) ~[spring-retry-1.2.1.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164) ~[spring-retry-1.2.1.RELEASE.jar:na]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:118) ~[spring-retry-1.2.1.RELEASE.jar:na]
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:152) ~[spring-retry-1.2.1.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$EnhancerBySpringCGLIB$$62f4e807.locate(<generated>) ~[spring-cloud-config-client-2.0.0.M1.jar:2.0.0.M1]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94) ~[spring-cloud-context-2.0.0.M1.jar:2.0.0.M1]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:624) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:364) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
	at com.bbb.microservices.sku.SkuMicroserviceApplication.main(SkuMicroserviceApplication.java:22) [classes/:na]
Caused by: org.springframework.web.client.HttpClientErrorException: 400 null
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:64) ~[spring-web-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:732) ~[spring-web-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:685) ~[spring-web-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:644) ~[spring-web-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:562) ~[spring-web-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.getRemoteEnvironment(ConfigServicePropertySourceLocator.java:172) ~[spring-cloud-config-client-2.0.0.M1.jar:2.0.0.M1]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:93) ~[spring-cloud-config-client-2.0.0.M1.jar:2.0.0.M1]
	... 17 common frames omitted

**Comment by mp911de** [comment]
Please don't cross-post.
