### ISSUE TITLE
LifecycleAwareSessionManager does not perform a re-login if token_max_ttl is reached

### ISSUE THREAD

**Issue by jogy** [spring-projects/spring-vault#176]
Consider the following scenario:

Vault is configured to use AppRole authentication (simplified so that it can be easly reproduced):

```
vault auth-enable approle
vault write auth/approle/role/my-app-role token_ttl=60s token_max_ttl=60s bind_secret_id=false bound_cidr_list=0.0.0.0/0
```

Spring Vault ist configured with AppRoleAuthentication and uses the role_id generated above. Token renewal is scheduled and successfully executed:

```
2017-11-15 12:27:39,421+01:00 DEBUG logger=o.s.v.a.AppRoleAuthentication - Login successful using AppRole authentication
2017-11-15 12:27:39,421+01:00 INFO  logger=o.s.v.a.LifecycleAwareSessionManager - Scheduling Token renewal
2017-11-15 12:28:34,421+01:00 INFO  logger=o.s.v.a.LifecycleAwareSessionManager - Renewing token
2017-11-15 12:28:34,436+01:00 INFO  logger=o.s.v.a.LifecycleAwareSessionManager - Scheduling Token renewal
```

The problem is that the token expires at 2017-11-15 12:28:39, i.e. 5 secs after its renewal it cannot be used anymore. So until the next renewal (which fails and will trigger a re-login) the token is invalid and requests get a 403 permission denied:

```
2017-11-15 12:29:03,532+01:00 ERROR logger=o.s.b.w.s.ErrorPageFilter - Forwarding to error page from request [/api/vault/...] due to exception [Status 403 sys/policy/...: permission denied]
org.springframework.vault.VaultException: Status 403 sys/policy/...: permission denied
        at org.springframework.vault.client.VaultResponses.buildException(VaultResponses.java:83)
        at org.springframework.vault.core.VaultTemplate.write(VaultTemplate.java:277)
2017-11-15 12:29:29,482+01:00 DEBUG logger=o.s.v.a.LifecycleAwareSessionManager - Cannot refresh token, resetting token and performing re-login: permission denied
```

In this case I would expect a re-login instead of a renewal. 

BTW. According to Vault source AppRole login tokens are always renewable. I found no way to turn it off: https://github.com/hashicorp/vault/blob/017c0ec283e874758164690a4e40500ac9042e1a/builtin/credential/approle/path_login.go#L70

**Comment by mp911de** [comment]
Thanks for your bug report. `LifecycleAwareSessionManager` does not consider the remaining TTL after renewal but sticks to the initial value and it does not react to a short remaining TTL.

To fix that, we need to read the remaining TTL after renewal and do two things:

1. Update the token with the remaining TTL
2. If the remaining TTL is less than the time until next renewal, then we should discard the token (revoke it) so the next access to a token will trigger a re-login.

Regarding

> BTW. According to Vault source AppRole login tokens are always renewable. I found no way to turn it off: 

I've to admit that I don't get that point.

**Comment by jogy** [comment]
Regarding the BTW: `LifecycleAwareSessionManager.isTokenRenewable()` will always return true for AppRole Login tokens. I tried to work around this bug but found no way. If the bug is fixed it won't matter anymore.

**Comment by mp911de** [comment]
Thanks for clarifying. `LifecycleAwareSessionManager` isn't restricted to be used with AppRole. You can use it with static tokens which may non-renewable.

**Comment by mp911de** [comment]
That's fixed now. Care to give the snapshot a spin?

```xml
<dependency>
  <groupId>org.springframework.vault</groupId>
  <artifactId>spring-vault</artifactId>
  <version>1.1.1.BUILD-SNAPSHOT</version>
</dependency>

<repository>
  <id>spring-libs-snapshot</id>
  <name>Spring Snapshot Repository</name>
  <url>http://repo.spring.io/libs-snapshot</url>
</repository>
```

**Comment by jogy** [comment]
Wow that was quick! I will try it out :)

**Comment by jogy** [comment]
Looks good, I'm not able to reproduce it anymore: 
```
2017-11-15 17:10:46,779+01:00 DEBUG logger=o.s.v.a.AppRoleAuthentication - Login successful using AppRole authentication
2017-11-15 17:10:46,780+01:00 INFO  logger=o.s.v.a.LifecycleAwareSessionManager - Scheduling Token renewal
2017-11-15 17:11:41,781+01:00 INFO  logger=o.s.v.a.LifecycleAwareSessionManager - Renewing token
2017-11-15 17:11:41,823+01:00 INFO  logger=o.s.v.a.LifecycleAwareSessionManager - Token TTL (4) exceeded validity TTL threshold (7000). Dropping token.
2017-11-15 17:12:22,519+01:00 DEBUG logger=o.s.v.a.AppRoleAuthentication - Login successful using AppRole authentication

```
