### ISSUE TITLE
VaultVersionedKeyValueTemplate error during retrieving metadata

### ISSUE THREAD

**Issue by nikoncode** [spring-projects/spring-vault#248]
During retrieving of created_time field I get an exception.

```
Caused by: java.time.DateTimeException: Unable to obtain Instant from TemporalAccessor: {OffsetSeconds=0},ISO resolved to 2018-04-24T10:47:18.110772748 of type java.time.format.Parsed
 at java.time.Instant.from(Instant.java:383) ~[?:1.8.0_11]
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: InstantSeconds
	at java.time.format.Parsed.getLong(Parsed.java:203) ~[?:1.8.0_11]

```

I think the problem is related to missing timezone info.

**Comment by nikoncode** [comment]
Java version 1.8.0_11

**Comment by mp911de** [comment]
Thanks a lot for pointing out the used Java version. The exception you see is a bug in the JDK library itself ([JDK-8033662](https://bugs.openjdk.java.net/browse/JDK-8033662)). Upgrading to at least Java 1.8.0_20 solves the issue.
