### ISSUE TITLE
ClientHttpRequestFactoryFactory checks for wrong Netty class on path (Spring Data Redis conflict)

### ISSUE THREAD

**Issue by dharrigan** [spring-projects/spring-vault#249]
HI,

I've been using Spring Data Vault 2.0.1 with Java 10 and Spring Boot 2.0.1 for the past few weeks very successfully (and happily). Recently a change was needed to introduce Redis as a Cache. I added the `spring-boot-starter-data-redis` dependency into my project to bring in what I required. This had the immediate (and surprising) result of causing Spring Vault to fail where before it worked. See below:

```
[2018-04-24 16:01:14,263] --- [DEBUG][o.s.web.client.RestTemplate             ][89  ] - Created GET request for "http://vault:8200/v1/auth/token/lookup-self"
[2018-04-24 16:01:14,267] --- [DEBUG][o.s.web.client.RestTemplate             ][860 ] - Setting request Accept header to [application/json, application/*+json]
[2018-04-24 16:01:14,301] --- [WARN ][io.netty.channel.ChannelInitializer     ][151 ] - Failed to initialize a channel. Closing: [id: 0x9f3be10b]
java.lang.ClassNotFoundException: io.netty.handler.codec.http.HttpClientCodec
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 19 common frames omitted
Wrapped by: java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpClientCodec
	at org.springframework.http.client.Netty4ClientHttpRequestFactory$1.initChannel(Netty4ClientHttpRequestFactory.java:211)
	at org.springframework.http.client.Netty4ClientHttpRequestFactory$1.initChannel(Netty4ClientHttpRequestFactory.java:202)
```

I tracked it down to `ClientHttpRequestFactoryFactory` and the static check of NETTY_PRESENT.

The thing is, Spring Boot Starter Data Redis brings in Netty, but *not* `netty-codec-http`. So, the `ClientHttpRequestFactoryFactory` thinks Netty is available, when in fact it isn't fully there because Spring Data Redis doesn't pull in all the required libraries. 

I believe it would be far safer to check if `io.netty.handler.codec.http.HttpClientCodec` is present before assuming Netty is available and keep with the default `SimpleClientHttpRequestFactory` if not. I don't want (or need) Netty for any Spring Vault operations as I'm quite happy with the defaults that have been working for weeks before.

Thank you!

-=david=-

**Comment by mp911de** [comment]
That's fixed now. I additionally included `SslContext` in the presence check to catch all direct module dependencies of `Netty4ClientHttpRequestFactory`.
