### ISSUE TITLE
Investigate support for PCF Login Method

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-vault#440]
Vault 1.2 comes with a Pivotal Cloud Foundry login mechanism that uses the container identity to perform a login.

We need to have a test environment to properly implement that mechanism.

**Comment by jbayer** [comment]
@tyrannosaurus-becks has made a sample code in this repo https://github.com/tyrannosaurus-becks/vault-tools-auth-pcf

**Comment by mp911de** [comment]
Thanks, James. The sample is helpful to get us started.

However, the mechanism to create proper signatures (RSA PSS) isn't available from the Java-bundled crypto support requiring us to pull in BouncyCastle for Java 8-10 runtimes. That's unfortunate as, optional libraries contribute to frustration on the user side, the only thing we can do is documentation. 

With Java 11, we get RSA PSS out of the box leaving us with two implementations.

**Comment by jbayer** [comment]
Makes sense Mark and yes that is unfortunate to deal with the extra dependency. On the plus side, this eventually goes away when Java 8 LTS expires. Thank you for your help.

**Comment by mp911de** [comment]
We have deployed a snapshot version `2.2.0.ISSUE-440-SNAPSHOT` containing PCF login support to https://repo.spring.io/snapshots.

```xml
<dependency>
	<groupId>org.springframework.vault</groupId>
	<artifactId>spring-vault-core</artifactId>
	<version>2.2.0.ISSUE-440-SNAPSHOT</version>
</dependency>
```

Docs for `PcfAuthentication`: https://github.com/spring-projects/spring-vault/blob/254f44c8fcb3171d8a1f23a2b35a585ed0fa9d0e/src/main/asciidoc/reference/authentication.adoc#pcf-authentication

**Comment by lanceplarsen** [comment]
We are testing on the snapshot and seeing the following error: 

```
  2019-08-01T18:27:34.70-0500 [APP/PROC/WEB/0] OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'CFAuthApplication': Invocation of init method failed; nested exception is org.springframework.vault.authentication.VaultLoginException: Cannot login using PCF: illegal base64 data at input byte 1; nested exception is org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request
```

I'm looking at the Base64Utils class and I think we need to use `encodeToUrlSafeString` instead of `encodeToString`.

**Comment by mp911de** [comment]
Do you have a full stack trace? Where does `illegal base64 data at input byte 1` come from?

**Comment by lanceplarsen** [comment]
Here's the stack trace: 

```
  2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'CFAuthApplication': Invocation of init method failed; nested exception is org.springframework.vault.authentication.VaultLoginException: Cannot login using PCF: illegal base64 data at input byte 6; nested exception is org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at com.example.demo.CFAuthApplication.main(CFAuthApplication.java:24) [classes/:na]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47) [app/:na]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:86) [app/:na]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app/:na]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT Caused by: org.springframework.vault.authentication.VaultLoginException: Cannot login using PCF: illegal base64 data at input byte 6; nested exception is org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.vault.authentication.VaultLoginException.create(VaultLoginException.java:64) ~[spring-vault-core-2.2.0.ISSUE-440-SNAPSHOT.jar!/:2.2.0.ISSUE-440-SNAPSHOT]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.vault.authentication.PcfAuthentication.login(PcfAuthentication.java:126) ~[spring-vault-core-2.2.0.ISSUE-440-SNAPSHOT.jar!/:2.2.0.ISSUE-440-SNAPSHOT]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.vault.authentication.LifecycleAwareSessionManager.doGetSessionToken(LifecycleAwareSessionManager.java:297) ~[spring-vault-core-2.2.0.ISSUE-440-SNAPSHOT.jar!/:2.2.0.ISSUE-440-SNAPSHOT]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.vault.authentication.LifecycleAwareSessionManager.getSessionToken(LifecycleAwareSessionManager.java:283) ~[spring-vault-core-2.2.0.ISSUE-440-SNAPSHOT.jar!/:2.2.0.ISSUE-440-SNAPSHOT]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at com.example.demo.CFAuthApplication.initIt(CFAuthApplication.java:29) [classes/:na]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	... 25 common frames omitted
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:79) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:414) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.vault.authentication.PcfAuthentication.login(PcfAuthentication.java:115) ~[spring-vault-core-2.2.0.ISSUE-440-SNAPSHOT.jar!/:2.2.0.ISSUE-440-SNAPSHOT]
   2019-08-02T10:23:45.42-0500 [APP/PROC/WEB/0] OUT 	... 35 common frames omitted
```

We made the encoding change locally and it fixed the issue.

**Comment by mp911de** [comment]
Thanks @lanceplarsen.

> I'm looking at the Base64Utils class and I think we need to use encodeToUrlSafeString instead of encodeToString.

You're right, Vault requires for this specific field URL-safe Base64-encoding.
Is there any good reason why this is and every other single Base64 field uses the regular encoding type? It's a JSON body and e.g. Transit has similar requirements.

The auth mechanism implementation is broken from a Java perspective with all these surprises and the use of a signature that is not natively available for the majority of Java production environments.

**Comment by jbayer** [comment]
Linking this related issue here for reference: https://github.com/hashicorp/vault-plugin-auth-pcf/issues/25

**Comment by kalafut** [comment]
A PR is up for the base64 encoding. Note that this introduces a `signature_version` parameter, which if omitted keeps the current behavior.  https://github.com/hashicorp/vault-plugin-auth-pcf/issues/25
