### ISSUE TITLE
LifecycleAwareSessionManager throwing 403 Forbidden when application is shutting down

### ISSUE THREAD

**Issue by AttitudeL** [spring-projects/spring-vault#567]
Dear all,

I've recently noticed some weird behaviour whenever my application is shutting down or getting a restart. The error message can be seen below.

```
org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: [{"errors":["permission denied"]}
]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:109) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:170) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:112) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:418) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.vault.authentication.LifecycleAwareSessionManager.revoke(LifecycleAwareSessionManager.java:180) ~[spring-vault-core-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_252]
	at org.springframework.vault.authentication.LifecycleAwareSessionManager.destroy(LifecycleAwareSessionManager.java:168) ~[spring-vault-core-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:258) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:579) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:551) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1091) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:512) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1084) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1029) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:168) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
```

I searched for the code where this exception is thrown. It appears to be the "revoke" method from "LifecycleAwareSessionManager". This method is trying to send a POST request to path "auth/token/revoke-self" upon application shutdown but then this request gets rejected due to no permission.

Please note that my application runs perfectly before the shutdown. It was able to read secret from vault using the approle auth.

Could someone please take a look at this? Much appreciated!

**Comment by mp911de** [comment]
Revoke self is expected on app shutdown to invalidate the token.

**Comment by AttitudeL** [comment]
> Revoke self is expected on app shutdown to invalidate the token.

Thanks for the reply. I'm aware that this self revoke is performed before shutting down the app. However due to 403 permission denied this request failed to be sent. I don't know that's causing it. My vault has been unsealed the whole time.

**Comment by mp911de** [comment]
403 means forbidden which is likely caused due to insufficient permissions on the role that is assigned to the login token.

**Comment by AttitudeL** [comment]
> 403 means forbidden which is likely caused due to insufficient permissions on the role that is assigned to the login token.

I see, thanks for the diagnose, I will check my approle settings and see if this is the reason.

**Comment by mp911de** [comment]
Closing this ticket at it looks that the issue was solved.
