### ISSUE TITLE
AWS IAM authentication login fails with Caused by: java.lang.IllegalArgumentException: URI is not absolute

### ISSUE THREAD

**Issue by wattry** [spring-projects/spring-vault#671]
When trying to use the org.springframework.vault.authentication.AwsIamAuthentication package the application throws the following error

```java
Exception in thread "main" java.lang.reflect.InvocationTargetException
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
  at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
  at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
  at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalArgumentException: URI is not absolute
  at java.net.URI.toURL(URI.java:1088)
  at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:141)
  at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:85)
  at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:648)
  at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
  at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:380)
  at org.springframework.vault.authentication.AwsIamAuthentication.createTokenUsingAwsIam(AwsIamAuthentication.java:142)
  at org.springframework.vault.authentication.AwsIamAuthentication.login(AwsIamAuthentication.java:126)
```

The line that seems to be making the request is 

```
VaultResponse response = this.vaultRestOperations
    .postForObject(AuthenticationUtil.getLoginPath(this.options.getPath()), login, VaultResponse.class);
```

Where `AuthenticationUtil.getLoginPath(this.options.getPath()` resolves to `String.format("auth/%s/login", authMount) -> auth/aws/login.` which itself is not a full path. 

We are using a base RestTemplate client which appears to be what a few examples reference. Below is the code snippet of the login being performed.

```java
package edu.vt.nis.web;

import com.amazonaws.auth.DefaultAWSCredentialsProviderChain;
import org.springframework.vault.authentication.AwsIamAuthenticationOptions;
import org.springframework.vault.authentication.AwsIamAuthentication;
import org.springframework.vault.authentication.AwsIamAuthenticationOptions.AwsIamAuthenticationOptionsBuilder;
import org.springframework.web.client.RestTemplate;
import org.springframework.vault.support.VaultToken;

public class VaultAws {
  private static final String VAULT_SERVER = System.getenv("VAULT_HEADER");
  private static final String VAULT_ROLE = System.getenv("VAULT_ROLE");

  private AwsIamAuthenticationOptions build() {
    DefaultAWSCredentialsProviderChain credentialsProvider = DefaultAWSCredentialsProviderChain.getInstance();
    AwsIamAuthenticationOptionsBuilder builder = AwsIamAuthenticationOptions.builder();

    return builder
      .role(VAULT_ROLE)
      .serverId(VAULT_SERVER)
      .credentialsProvider(credentialsProvider)
      .build();
  }

  private AwsIamAuthentication login() {
    RestTemplate restTemplate = new RestTemplate();
    AwsIamAuthenticationOptions options = build();

    return new AwsIamAuthentication(options, restTemplate).login();
  }
}
```

**Comment by wattry** [comment]
Come to find out I had to use CommandLine runner to and a RestTemplateBuilder to get the https request working. Issue is now that the uri explicitly asks for '/' paths when a root uri is set. However, `AuthenticationUtil.getLoginPath(this.options.getPath()` resolves to auth/aws/login not /auth/aws/login.

**Comment by wattry** [comment]
Found a solution in nodejs ([ldapts](https://github.com/ldapts/ldapts)) so we canned the java implementation
