### ISSUE TITLE
Add support to obtain PEM-encoded certificates as `X509Certificate`

### ISSUE THREAD

**Issue by abremora** [spring-projects/spring-vault#678]
`Certificate.getX509Certificate()` and `Certificate.getX509IssuerCertificate()` do not support conversion of PEM-encoded string to X509Certificate.

**Comment by abremora** [comment]
It's odd in that the default of the returned data is PEM.

> format (string: "") – Specifies the format for returned data. Can be pem, der, or pem_bundle; defaults to pem. 
> If der, the output is base64 encoded. If pem_bundle, the certificate field will contain the private key and certificate, 
> concatenated; if the issuing CA is not a Vault-derived self-signed root, this will be included as well.

https://www.vaultproject.io/api-docs/secret/pki#generate-certificate

**Comment by abremora** [comment]
Same issue affects  `CertificateBundle.createKeyStore()` & `CertificateBundle.getPrivateKeySpec()`, too. (Already mentioned in the documentation)

```
java.lang.IllegalArgumentException: Illegal base64 character 2d
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:746) ~[na:na]
	at java.base/java.util.Base64$Decoder.decode(Base64.java:538) ~[na:na]
	at org.springframework.util.Base64Utils.decode(Base64Utils.java:59) ~[spring-core-5.3.13.jar:5.3.13]
	at org.springframework.util.Base64Utils.decodeFromString(Base64Utils.java:111) ~[spring-core-5.3.13.jar:5.3.13]
	at org.springframework.vault.support.CertificateBundle.getPrivateKeySpec(CertificateBundle.java:89) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.support.CertificateBundle.createKeyStore(CertificateBundle.java:109) ~[spring-vault-core-2.3.2.jar:2.3.2]
````

**Comment by abremora** [comment]
Just for clarification: For `Vault` the default is PEM but for `spring-vault` the default is DER:

https://github.com/spring-projects/spring-vault/blob/26a77a2199ecd5186f04c930c2062ef7bb4711ee/spring-vault-core/src/main/java/org/springframework/vault/core/VaultPkiTemplate.java#L91

I will fix this issue within the next days.

**Comment by abremora** [comment]
Of course we cannot change the behavior of vault-spring but we have to support other formats and improve documentation.
