### ISSUE TITLE
Support elliptic curve keys in `CertificateBundle` 

### ISSUE THREAD

**Issue by abremora** [spring-projects/spring-vault#683]
# Description

No keystore can be created when the private key is of type `private_key_type=ec`.

```
java.lang.IllegalStateException: Invalid DER: object (4) is not integer.
	at org.springframework.vault.support.KeystoreUtil$Asn1Object.getInteger(KeystoreUtil.java:502) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.support.KeystoreUtil.getRSAPrivateKeySpec(KeystoreUtil.java:255) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.support.CertificateBundle.getPrivateKeySpec(CertificateBundle.java:90) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.support.CertificateBundle.createKeyStore(CertificateBundle.java:109) ~[spring-vault-core-2.3.2.jar:2.3.2]
````

# Solution
Fix `CertificateBundle` and its dependencies like ` KeystoreUtil` which are focused on RSA implementation.

**Comment by abremora** [comment]
I have a working version but I use Bouncy Castle for EC support. Is there anything we need to consider when using third party libs?

**Comment by mp911de** [comment]
`KeystoreUtil` is a core utility that should remain free of 3rd-party dependencies.

**Comment by abremora** [comment]
I didn't use the `KeystoreUtil` for EC implementation. All details are implemented in a separate class. Currently Bouncy Castle is an optional dependency in spring-vault, so we have to include BC only when EC should be used. Is this an option?

**Comment by mp911de** [comment]
I think so. We can guard the access to BC and document that requirement. But it's not something that is obvious. Ideally, we would have an EC-capable certificate/key parser in our code.

**Comment by abremora** [comment]
However, there is already an existing implementation in BC for our problem and it is quite easy to use:
```java
private static java.security.spec.ECPrivateKeySpec getEcPrivateKeySpec(byte[] privateKey) {
    ECPrivateKey ecPrivateKey = ECPrivateKey.getInstance(privateKey);
    ASN1ObjectIdentifier parameters = (ASN1ObjectIdentifier) ecPrivateKey.getParameters();

    X9ECParameters curveParameter = X962NamedCurves.getByOID(parameters);

    EllipticCurve ellipticCurve = new EllipticCurve(
            new ECFieldFp(curveParameter.getCurve().getField().getCharacteristic()),
            curveParameter.getCurve().getA().toBigInteger(), curveParameter.getCurve().getB().toBigInteger());

    ECPoint gPoint = new ECPoint(curveParameter.getG().getXCoord().toBigInteger(),
            curveParameter.getG().getYCoord().toBigInteger());

    ECParameterSpec paramSpec = new ECParameterSpec(ellipticCurve, gPoint, curveParameter.getN(),
            curveParameter.getH().intValue());

    return new java.security.spec.ECPrivateKeySpec(ecPrivateKey.getKey(), paramSpec);
}
```
Are there any other implementations we can use? I am not an expert in cryptography, so I do not want to rewrite this myself.
