### ISSUE TITLE
AOT processing error

### ISSUE THREAD

**Issue by acs900** [spring-projects/spring-vault#750]
When running a spring native build, you get this error during the AOT processing step:

`[INFO] --- spring-boot-maven-plugin:3.0.2:process-aot (process-aot) @ demo` 
... snip ...
`2023-02-07T06:59:01.866-06:00  INFO 2011 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=7c222016-cdd5-375e-becb-b0b529f2f628
Exception in thread "main" java.lang.IllegalStateException: No constructor or factory method candidate found for Root bean: class [org.springframework.vault.client.RestTemplateFactory]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null and argument types []
        at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorOrFactoryMethod(ConstructorResolver.java:944)
        at org.springframework.beans.factory.support.RegisteredBean.resolveConstructorOrFactoryMethod(RegisteredBean.java:197)`

**Comment by mp911de** [comment]
This is because the AOT support is being shipped with #747
