### ISSUE TITLE
java.lang.ClassNotFoundException after upgrade to 3.0.2

### ISSUE THREAD

**Issue by grmblfrz** [spring-projects/spring-vault#786]
After upgrading spring-vault-core from 3.0.1 to 3.0.2 my application no longer starts. It fails with `java.lang.ClassNotFoundException: software.amazon.awssdk.auth.credentials.AwsCredentialsProvider`. Is the dependency to `com.amazonaws:aws-java-sdk-core` mandatory even if not using AWS-IAM authentication?

**Comment by mp911de** [comment]
This sounds like a bug. Can you attach the full stack trace so we get the detail where the exception is being thrown?

**Comment by grmblfrz** [comment]
Please find attached the stacktrace (packages / source file names partially redacted):
[stacktrace-redacted.txt](https://github.com/spring-projects/spring-vault/files/11287350/stacktrace-redacted.txt)

**Comment by mp911de** [comment]
```
java.lang.IllegalStateException: Failed to introspect Class [xx.xxx.xxxxxxx.backend.config.VaultPropertiesConfiguration] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@6f496d9f]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:483)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:360)
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:417)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$1(AbstractAutowireCapableBeanFactory.java:748)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:747)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:680)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:651)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1632)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:560)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:532)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:252)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:245)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:235)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:183)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:158)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
	... 25 common frames omitted
Caused by: java.lang.NoClassDefFoundError: software/amazon/awssdk/auth/credentials/AwsCredentialsProvider
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465)
	... 41 common frames omitted
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.auth.credentials.AwsCredentialsProvider
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 45 common frames omitted
```

This exception shows a failure originating from your class `xx.xxx.xxxxxxx.backend.config.VaultPropertiesConfiguration`. I suggest that you set a breakpoint in the `ClassNotFoundException` constructor and that you take a look with the debugger, where this comes from.

**Comment by grmblfrz** [comment]
Here is a small sample project:
[vaultbugdemo.tar.gz](https://github.com/spring-projects/spring-vault/files/11287864/vaultbugdemo.tar.gz)
(with 3.0.2 it will crash with ClassNotFoundException, with 3.0.1 it will crash because of missing keystore, which is expected).

**Comment by mp911de** [comment]
Thanks a lot, this makes things much easier.

**Comment by mp911de** [comment]
That's fixed now. Care to test against the latest `3.0.3-SNAPSHOT`?

**Comment by grmblfrz** [comment]
I can confirm it works with 3.0.3-SNAPSHOT.
